-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) TOTAL_SALES
FROM BOOK
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID  
JOIN BOOK_SALES WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND SALES_DATE < '2022-02-01' 
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC

# SELECT BOOK_SALES.BOOK_ID, SALES_DATE, SALES 
# FROM BOOK_SALES
# JOIN BOOK WHERE BOOK_SALES.BOOK_ID = BOOK.BOOK_ID AND SALES_DATE < '2022-02-01'
# GROUP BY BOOK_SALES.BOOK_ID

# SELECT BOOK.AUTHOR_ID, CATEGORY, AUTHOR_NAME, PRICE
# FROM AUTHOR
# JOIN BOOK 
# WHERE AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID